# Generated by Django 4.2 on 2023-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_remove_publication_pub_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
